COMP: Fix build accounting for vtkVirtualRealityViewInteractor API change
This commit renames the function from HandleGripEvents to HandleComplexGestureEvents
to account for the change introduced through VTK MR-9892.

See https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9892

It fixes error like the following:

In file included from /path/to/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.cxx:21:
/path/to/SlicerVirtualReality/VirtualReality/MRML/vtkVirtualRealityViewInteractor.h:49:16: error: ‘virtual void vtkVirtualRealityViewInteractor::HandleGripEvents(vtkEventData*)’ marked ‘override’, but does not override
   49 |   virtual void HandleGripEvents(vtkEventData* ed) override;
      |                ^~~~~~~~~~~~~~~~